services:
  # 웹서버 컨테이너
  web:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.3/app
    container_name: wca-web
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}"
      TZ: '${APP_TIMEZONE}'
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    command: php artisan serve --host=0.0.0.0 --port=80

  # 큐워커 컨테이너 (확장 가능)
  queue:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.3/app
    container_name: wca-queue
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      TZ: '${APP_TIMEZONE}'
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - web
    command: php artisan queue:work --tries=3 --timeout=90 --max-jobs=1000

  # 스케줄러 컨테이너
  scheduler:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP}"
    image: sail-8.3/app
    container_name: wca-scheduler
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      WWWUSER: "${WWWUSER}"
      LARAVEL_SAIL: 1
      TZ: '${APP_TIMEZONE}'
    volumes:
      - ".:/var/www/html"
    networks:
      - sail
    depends_on:
      - web
    command: php artisan schedule:work

networks:
  sail:
    driver: bridge