services:
  # Laravel 애플리케이션 컨테이너 (Nginx + PHP-FPM)
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
      args:
        WWWGROUP: '${WWWGROUP:-1000}'
        WWWUSER: '${WWWUSER:-1000}'
    image: wca-app:latest
    container_name: wca-app
    restart: always
    ports:
      - "${APP_PORT:-80}:80"
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      TZ: '${APP_TIMEZONE:-Asia/Seoul}'
    volumes:
      - .:/var/www/html
    networks:
      - wca-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  # 큐워커 컨테이너
  queue:
    image: wca-app:latest
    container_name: wca-queue
    restart: always
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      TZ: '${APP_TIMEZONE:-Asia/Seoul}'
    volumes:
      - .:/var/www/html
    networks:
      - wca-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
    command: php artisan queue:work --tries=3 --timeout=90 --max-jobs=1000 --sleep=3

  # 스케줄러 컨테이너
  scheduler:
    image: wca-app:latest
    container_name: wca-scheduler
    restart: always
    environment:
      WWWUSER: '${WWWUSER:-1000}'
      TZ: '${APP_TIMEZONE:-Asia/Seoul}'
    volumes:
      - .:/var/www/html
    networks:
      - wca-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
    command: php artisan schedule:work

networks:
  wca-network:
    driver: bridge
