<?php

return [
    'NICE_PAY_VIRTUAL_ACCOUNT_URL' => env('NICE_PAY_VIRTUAL_ACCOUNT_URL', null),
    'NICE_PAY_VIRTUAL_ACCOUNT_CLIENT_KEY' => env('NICE_PAY_VIRTUAL_ACCOUNT_CLIENT_KEY', null),
    'NICE_PAY_VIRTUAL_ACCOUNT_CLIENT_ID' => env('NICE_PAY_VIRTUAL_ACCOUNT_CLIENT_ID', null),
];

